spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

server:
  port: 8091

logging:
  level:
    com.lenovo.orderservice: debug
    org.apache.kafka: warn
    org.springframework.kafka: warn

product-service:
  url: http://localhost:8090

swagger:
  api:
    title: Order Service API
    description: Service for managing orders
    version: 1.0

application:
  web-security-config:
    custom-unsecured-endpoints:
